### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by mc0re** [boyanio/react-blazor#14]
Running `npm run build` yields the following error:

```
> react-blazor@0.1.0 build:react
> webpack

i ｢atl｣: Using typescript@3.3.1 from typescript
i ｢atl｣: Using tsconfig.json from C:/Projects/Experiments/React-Blazor/tsconfig.json
Error in bail mode: Error: callback(): The callback was already called.
    at context.callback (C:\Projects\Experiments\React-Blazor\node_modules\loader-runner\lib\LoaderRunner.js:106:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) Error: callback(): The callback was already called.
    at context.callback (C:\Projects\Experiments\React-Blazor\node_modules\loader-runner\lib\LoaderRunner.js:106:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Updating `webpack` and `webpack-cli` leads to 50+ syntax errors.

**Comment by boyanio** [comment]
Hey. I have upgraded most dependencies. I will close this issue for now, but feel free to open another one if the problem still persists for you.
